name: Check Metrics Collinearity

on:
  pull_request:
    paths:
      - 'flashcamp/data/**.csv'
      - 'flashcamp/backend/contracts/metrics.json'
      - 'flashcamp/frontend/constants/metrics.json'
  push:
    branches: [ main ]
    paths:
      - 'flashcamp/data/**.csv'
      - 'flashcamp/backend/contracts/metrics.json'
      - 'flashcamp/frontend/constants/metrics.json'

jobs:
  check-collinearity:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pytest
        
    - name: Run collinearity test
      run: |
        python -m pytest tests/test_metrics_collinearity.py -v 